from . import test_course
from . import test_cv
from . import test_education
from . import test_experience
from . import test_personalprofile
from . import test_project
from . import test_responsibility
from . import test_skill
from . import test_tag
from . import test_views_homepage
