language: python
python:
  - 3.5
install:
  - pip install -r requirements.txt
script:
  - cd cvtool
  - python manage.py migrate --run-syncdb
  - coverage run --source="." --omit="cvtool/*" manage.py test cv
  - coverage report
  - python manage.py behave --tags @fixtures
  - cd ..
  - pylint --load-plugins pylint_django cvtool/cv
  - flake8 cvtool
after_success:
  - coveralls