# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-02 21:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of skill', max_length=256)),
                ('proficiency', models.CharField(choices=[('NP', 'No Proficiency'), ('BU', 'Basic Understanding'), ('WK', 'Working Knowledge'), ('AK', 'Advanced Knowledge'), ('EK', 'Expert Knowledge')], default='BU', help_text='Proficiency of skill', max_length=2)),
                ('freshness', models.CharField(choices=[('NCP', 'Not Current Practice'), ('OOD', 'Out of Date'), ('OWO', 'On Way Out'), ('CBP', 'Current Practice'), ('NAY', 'Not Widely Adopted Yet')], default='CBP', help_text='Is skill current practice?', max_length=3)),
                ('tags', models.ForeignKey(help_text='Tags for skill', on_delete=django.db.models.deletion.CASCADE, to='cv.Tag')),
            ],
        ),
    ]
