# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-02 22:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0003_auto_20160402_2155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='skill',
        ),
        migrations.AddField(
            model_name='skill',
            name='tag',
            field=models.ManyToManyField(related_name='tag', to='cv.Tag'),
        ),
    ]
