# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-02 22:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0004_auto_20160402_2201'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill',
            old_name='tag',
            new_name='tags',
        ),
    ]
