# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-02 23:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0010_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(help_text='Institution studied at', max_length=256)),
                ('start_date', models.DateField(help_text='Date started studies')),
                ('end_date', models.DateField(blank=True, help_text='Date ended studies', null=True)),
                ('courses', models.ManyToManyField(to='cv.Course')),
                ('projects', models.ManyToManyField(to='cv.Project')),
            ],
        ),
        migrations.AlterField(
            model_name='experience',
            name='projects',
            field=models.ManyToManyField(to='cv.Project'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='responsibilities',
            field=models.ManyToManyField(to='cv.Responsibility'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='tags',
            field=models.ManyToManyField(to='cv.Tag'),
        ),
    ]
