# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-02 23:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0011_auto_20160402_2307'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Your name', max_length=256)),
                ('email', models.EmailField(help_text='Your email address', max_length=254)),
                ('website', models.URLField(help_text='Your website URL')),
                ('portfolio', models.URLField(help_text='Your portfolio URL')),
                ('personal_statement', models.TextField(help_text='Personal Statement to summarise who you are')),
            ],
        ),
    ]
