# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-02 23:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0012_personalprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='CV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='name of CV', max_length=256)),
                ('education', models.ManyToManyField(help_text='Education to use', to='cv.Education')),
                ('experiences', models.ManyToManyField(help_text='Experiences to use', to='cv.Experience')),
                ('personal_profile', models.ForeignKey(help_text='Personal Profile to use', on_delete=django.db.models.deletion.CASCADE, to='cv.PersonalProfile')),
                ('skills', models.ManyToManyField(help_text='Skills to use', to='cv.Skill')),
            ],
        ),
    ]
